services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: online-biblioteca-api
    environment:
      - NODE_ENV=production
      # Cambia este valor en producción
      - JWT_SECRET=super_secret_jwt_key
      - PORT=4000
    ports:
      - "4000:4000"
    volumes:
      # Montar la base de datos para persistencia y posibles cambios
      - ./database/db.json:/app/database/db.json
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # URL que usará el navegador para llamar a la API desde el host
        VITE_URL_API: http://localhost:4000
    container_name: online-biblioteca-web
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped
